name: profile
description: Profile project.
publish_to: "none"

homepage: "https://abianche.github.io/"
issue_tracker: "https://github.com/abianche/profile/issues"
repository: "https://github.com/abianche/profile"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/images/
